language: java

install:
    - mvn -DpdiInstall=false -DpdiInstallDir=./target/pdi/plugins/steps/ic-riak-plugin -DskipTests=true -B -V clean

script:
    - mvn -DpdiInstall=false -DpdiInstallDir=./target/pdi/plugins/steps/ic-riak-plugin package

after_success:
    - mvn clean cobertura:cobertura coveralls:cobertura

deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: ./target/ic-riak-plugin-pdi-*.zip
    skip_cleanup: true
    on:
        tags: true
env:
  global:
    secure: OqqcOYCPHdBfoVGR0GxUcG/VaUgjov+jRnuUN2mWdDEbRvzMcrQ6UzLP8fSa9UE9auW7B3VYPBzE4ScdhaiIkaSRh87KziJsl/61EraZLTp1DAYBXIKQuDA49EGQFKF3vktXWtqoUPpdlAeOSG6JXqo7lF61MmJHAMEmnUE0Sjc=
