language: java

install:
    - mvn -DskipTests=true dependency:resolve

script:
    - mvn clean package

after_success:
    - mvn cobertura:cobertura coveralls:cobertura
    - mvn -DskipTests=true clean package

deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: ./target/ic-riak-plugin-pdi-*.zip
    skip_cleanup: true
    on:
        tags: true
